language: php
php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
